### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by AndyDiep** [xh4n3/angularjs-paste-upload#1]
tested but had no luck with it.
it seems angular does not play nice with clipboard binary data.

**Comment by xh4n3** [comment]
Thanks for the issue, I pushed another fix, hope it helps.
TIPS,
1. Before you try upload, make sure you've change the POST target url, it has to be online, not on the localhost. Or your browser would give out errors.
2. You can use console.log() to print out the clipData or img, to see if they're working.
3. Besides, make sure you are copying the real pictures before you paste them into the textarea, copying picture files in the file system doesn't count, you can try copying pictures from office word.
4. This tiny feature has been imported into my zone_blog repo, have a look if you have any further problem.

**Comment by AndyDiep** [comment]
After jumped through hoops and finally got it working.
Well worth the effort though.
Its killer feature and all web apps should have it.:)
Thanks for sharing.
Cheer!

**Comment by xh4n3** [comment]
:smile: 
Thanks for using!
